# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 06:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_address', models.CharField(max_length=200)),
                ('form_phone_number', models.CharField(max_length=13)),
                ('form_belongs_to_institution', models.CharField(max_length=200)),
                ('form_belongs_to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
