# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=13)),
                ('book_price', models.PositiveIntegerField()),
                ('book_author_contact', models.CharField(blank=True, max_length=13, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='form',
            name='form_belongs_to_user',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
    ]
